Fix json_reformat, yajl_test and gen-extra-close linking with uClibc
json_reformat, yajl_test and gen-extra-close call yajl_gen_* functions,
which internally use isnan() and isinf(). On glibc, these are provided
by libc, but on uClibc you need to link with -lm (like the spec says),
otherwise the build process will fail with an error like this one:

yajl_gen.c:(.text+0x67c): undefined reference to `__isnan'
yajl_gen.c:(.text+0x70c): undefined reference to `__isinf'

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>