cmake: uClibc: Fix missing libm for tests
At the link time, the tests are not linked against libm which cause an
error with uClibc based toolchain:

../../yajl-2.1.0/lib/libyajl.so.2.1.0: undefined reference to `__isnan'
../../yajl-2.1.0/lib/libyajl.so.2.1.0: undefined reference to `__isinf'

Signed-off-by: Maxime Hadjinlian <maxime.hadjinlian@gmail.com>